export const EXPRESSION_ASSIST_STATE_SCHEMA_VERSION = 3;
export const EXPRESSION_ASSIST_FLOW_VERSION = 5;

export const EXPRESSION_ASSIST_GRAPH_MODES = Object.freeze({
    OFF: "off",
    SHADOW: "shadow",
    AUTHORITY: "authority",
});

export const EXPRESSION_INTERVENTION_ACTIONS = Object.freeze({
    NO_ACTION: "NO_ACTION",
    SOFT_RECAST: "SOFT_RECAST",
    CLARIFY: "CLARIFY",
    EXPRESSION_CARD: "EXPRESSION_CARD",
});

export const EXPRESSION_ASSIST_EVENT_TYPES = Object.freeze({
    RUN_STARTED: "RUN_STARTED",
    FREE_CHAT_TURN_COMPLETED: "FREE_CHAT_TURN_COMPLETED",
    CONTEXT_RESET: "CONTEXT_RESET",
    CARD_EFFECT_CLAIMED: "CARD_EFFECT_CLAIMED",
    CARD_EFFECT_COMPLETED: "CARD_EFFECT_COMPLETED",
    CARD_EFFECT_FAILED: "CARD_EFFECT_FAILED",
});

export const EXPRESSION_ASSIST_EFFECT_TYPES = Object.freeze({
    PRESENT_EXPRESSION_CARD: "PRESENT_EXPRESSION_CARD",
});

export const EXPRESSION_ASSIST_EFFECT_STATUS = Object.freeze({
    PENDING: "PENDING",
    IN_PROGRESS: "IN_PROGRESS",
    COMPLETE: "COMPLETE",
    FAILED: "FAILED",
});

export const EXPRESSION_ASSIST_PROCESSED_EVENT_LIMIT = 100;
export const EXPRESSION_ASSIST_EFFECT_LIMIT = 20;
export const EXPRESSION_ASSIST_EFFECT_MAX_ATTEMPTS = 3;
export const EXPRESSION_ASSIST_EFFECT_LEASE_MS = 60_000;
export const EXPRESSION_ASSIST_MAX_TURN_CHARS = 4_000;
export const EXPRESSION_ASSIST_MAX_CONTEXT_MESSAGES = 3;
export const EXPRESSION_ASSIST_COOLDOWN_TURNS = 3;
export const EXPRESSION_ASSIST_COOLDOWN_MS = 45_000;
